name: Test StickWar

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: List files
      run: |
        echo "Files in repo:"
        find . -type f -name "*.gradle" -o -name "*.xml" -o -name "*.kt"
